# Generated by Django 4.2.16 on 2024-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0002_beer_drinks_bread_cold_drinks_dishes_to_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadbaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('lang', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
