# Generated by Django 4.2.16 on 2024-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_year',
            field=models.DateField(),
        ),
    ]
