# Generated by Django 4.2.16 on 2024-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0005_alter_order_time_of_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_year',
            field=models.DateTimeField(),
        ),
    ]
