# Generated by Django 4.2.16 on 2024-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0008_money_order_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece', models.IntegerField()),
                ('money', models.CharField(max_length=50)),
                ('time_of_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='money',
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
