# Generated by Django 4.2.16 on 2024-09-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0009_ordernew_remove_order_money_delete_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
