# Generated by Django 4.2.16 on 2024-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0010_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece', models.IntegerField()),
                ('time_of_year', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('1', 'Наличные'), ('2', 'Пластик')], default='1', max_length=1)),
            ],
        ),
    ]
